// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(LostFoundTrackingSystemContext))]
    [Migration("20251215132612_UpdateItemActionLogEncoding")]
    partial class UpdateItemActionLogEncoding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CampusName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CampusId")
                        .HasName("PK__Campus__FD598D36CC85AA0D");

                    b.ToTable("Campus", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__19093A2BEE731716");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ClaimRequest", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<DateTime?>("ClaimDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ClaimId")
                        .HasName("PK__ClaimReq__EF2E13BBBCB583AD");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClaimRequest", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Evidence", b =>
                {
                    b.Property<int>("EvidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvidenceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenceId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LostItemId")
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EvidenceId")
                        .HasName("PK__Evidence__FA39D78D0464995F");

                    b.HasIndex("CampusId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("LostItemId");

                    b.ToTable("Evidence", (string)null);
                });

            modelBuilder.Entity("DAL.Models.FoundItem", b =>
                {
                    b.Property<int>("FoundItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoundItemId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FoundDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FoundLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StoredBy")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FoundItemId")
                        .HasName("PK__FoundIte__DFA62C37CBB854E9");

                    b.HasIndex("CampusId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StoredBy");

                    b.ToTable("FoundItem", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("EvidenceId")
                        .HasColumnType("int")
                        .HasColumnName("EvidenceID");

                    b.Property<int?>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ImageURL");

                    b.Property<int?>("LostItemId")
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("ImageId")
                        .HasName("PK__Image__7516F4ECFA38BA08");

                    b.HasIndex("EvidenceId");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("LostItemId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ItemActionLog", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ActionDetails")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("ActionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int?>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<int?>("ClaimRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<int?>("LostItemId")
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Vietnamese_CI_AS");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.HasKey("ActionId")
                        .HasName("PK__ItemActi__FFE3F4B95A97F119");

                    b.HasIndex("CampusId");

                    b.HasIndex("ClaimRequestId");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("LostItemId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("ItemActionLog", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ItemMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<int?>("LostItemId")
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    b.Property<string>("MatchStatus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MatchId")
                        .HasName("PK__ItemMatc__4218C83709C4822E");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("LostItemId");

                    b.ToTable("ItemMatch", (string)null);
                });

            modelBuilder.Entity("DAL.Models.LostItem", b =>
                {
                    b.Property<int>("LostItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LostItemId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LostDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LostLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LostItemId")
                        .HasName("PK__LostItem__3B3BF43289AA9C74");

                    b.HasIndex("CampusId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("LostItem", (string)null);
                });

            modelBuilder.Entity("DAL.Models.MatchHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ActionBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    b.HasKey("HistoryId")
                        .HasName("PK__MatchHis__4D7B4ADDC3B60DB0");

                    b.HasIndex("ActionBy");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchHistory", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("ReferenceID");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32XXXXXXXX");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("IX_Notification_IsRead");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notification_UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DAL.Models.ReturnRecord", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int?>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<int?>("LostItemId")
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("ReceiverID");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("StaffUserId")
                        .HasColumnType("int")
                        .HasColumnName("StaffUserID");

                    b.HasKey("ReturnId")
                        .HasName("PK__ReturnRe__F445E9884665C768");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("StaffUserId");

                    b.HasIndex(new[] { "LostItemId" }, "UQ_ReturnRecord_LostItemId")
                        .IsUnique()
                        .HasFilter("[LostItemID] IS NOT NULL");

                    b.HasIndex(new[] { "FoundItemId" }, "UQ__ReturnRe__DFA62C36D4297726")
                        .IsUnique()
                        .HasFilter("[FoundItemID] IS NOT NULL");

                    b.ToTable("ReturnRecord", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A4E892C72");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCACBDF5688F");

                    b.HasIndex("CampusId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ClaimRequest", b =>
                {
                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithMany("ClaimRequests")
                        .HasForeignKey("FoundItemId")
                        .HasConstraintName("FK__ClaimRequ__Found__1332DBDC");

                    b.HasOne("DAL.Models.User", "Student")
                        .WithMany("ClaimRequests")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__ClaimRequ__Stude__14270015");

                    b.Navigation("FoundItem");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DAL.Models.Evidence", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Evidences")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__Evidence__Campus__17036CC0");

                    b.HasOne("DAL.Models.ClaimRequest", "Claim")
                        .WithMany("Evidences")
                        .HasForeignKey("ClaimId")
                        .HasConstraintName("FK__Evidence__ClaimI__151B244E");

                    b.HasOne("DAL.Models.LostItem", "LostItem")
                        .WithMany("Evidences")
                        .HasForeignKey("LostItemId")
                        .HasConstraintName("FK__Evidence__LostIt__160F4887");

                    b.Navigation("Campus");

                    b.Navigation("Claim");

                    b.Navigation("LostItem");
                });

            modelBuilder.Entity("DAL.Models.FoundItem", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("FoundItems")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__FoundItem__Campu__114A936A");

                    b.HasOne("DAL.Models.Category", "Category")
                        .WithMany("FoundItems")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__FoundItem__Categ__123EB7A3");

                    b.HasOne("DAL.Models.User", "CreatedByNavigation")
                        .WithMany("FoundItemCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__FoundItem__Creat__0F624AF8");

                    b.HasOne("DAL.Models.User", "StoredByNavigation")
                        .WithMany("FoundItemStoredByNavigations")
                        .HasForeignKey("StoredBy")
                        .HasConstraintName("FK__FoundItem__Store__10566F31");

                    b.Navigation("Campus");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("StoredByNavigation");
                });

            modelBuilder.Entity("DAL.Models.Image", b =>
                {
                    b.HasOne("DAL.Models.Evidence", "Evidence")
                        .WithMany("Images")
                        .HasForeignKey("EvidenceId")
                        .HasConstraintName("FK__Image__EvidenceI__25518C17");

                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithMany("Images")
                        .HasForeignKey("FoundItemId")
                        .HasConstraintName("FK__Image__FoundItem__245D67DE");

                    b.HasOne("DAL.Models.LostItem", "LostItem")
                        .WithMany("Images")
                        .HasForeignKey("LostItemId")
                        .HasConstraintName("FK_Image_LostItem");

                    b.HasOne("DAL.Models.User", "UploadedByNavigation")
                        .WithMany("Images")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("FK__Image__UploadedB__236943A5");

                    b.Navigation("Evidence");

                    b.Navigation("FoundItem");

                    b.Navigation("LostItem");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("DAL.Models.ItemActionLog", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("ItemActionLogs")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__ItemActio__Campu__22751F6C");

                    b.HasOne("DAL.Models.ClaimRequest", "ClaimRequest")
                        .WithMany()
                        .HasForeignKey("ClaimRequestId")
                        .HasConstraintName("FK_ItemActionLog_ClaimRequest");

                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithMany("ItemActionLogs")
                        .HasForeignKey("FoundItemId")
                        .HasConstraintName("FK__ItemActio__Found__208CD6FA");

                    b.HasOne("DAL.Models.LostItem", "LostItem")
                        .WithMany("ItemActionLogs")
                        .HasForeignKey("LostItemId")
                        .HasConstraintName("FK__ItemActio__LostI__1F98B2C1");

                    b.HasOne("DAL.Models.User", "PerformedByNavigation")
                        .WithMany("ItemActionLogs")
                        .HasForeignKey("PerformedBy")
                        .HasConstraintName("FK__ItemActio__Perfo__2180FB33");

                    b.Navigation("Campus");

                    b.Navigation("ClaimRequest");

                    b.Navigation("FoundItem");

                    b.Navigation("LostItem");

                    b.Navigation("PerformedByNavigation");
                });

            modelBuilder.Entity("DAL.Models.ItemMatch", b =>
                {
                    b.HasOne("DAL.Models.User", "CreatedByNavigation")
                        .WithMany("ItemMatches")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__ItemMatch__Creat__19DFD96B");

                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithMany("ItemMatches")
                        .HasForeignKey("FoundItemId")
                        .HasConstraintName("FK__ItemMatch__Found__17F790F9");

                    b.HasOne("DAL.Models.LostItem", "LostItem")
                        .WithMany("ItemMatches")
                        .HasForeignKey("LostItemId")
                        .HasConstraintName("FK__ItemMatch__LostI__18EBB532");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("FoundItem");

                    b.Navigation("LostItem");
                });

            modelBuilder.Entity("DAL.Models.LostItem", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("LostItems")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK_LostItem_Campus");

                    b.HasOne("DAL.Models.Category", "Category")
                        .WithMany("LostItems")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__LostItem__Catego__0E6E26BF");

                    b.HasOne("DAL.Models.User", "CreatedByNavigation")
                        .WithMany("LostItems")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__LostItem__Create__0D7A0286");

                    b.Navigation("Campus");

                    b.Navigation("Category");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("DAL.Models.MatchHistory", b =>
                {
                    b.HasOne("DAL.Models.User", "ActionByNavigation")
                        .WithMany("MatchHistories")
                        .HasForeignKey("ActionBy")
                        .HasConstraintName("FK__MatchHist__Actio__1BC821DD");

                    b.HasOne("DAL.Models.ItemMatch", "Match")
                        .WithMany("MatchHistories")
                        .HasForeignKey("MatchId")
                        .HasConstraintName("FK__MatchHist__Match__1AD3FDA4");

                    b.Navigation("ActionByNavigation");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("DAL.Models.Notification", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Notification__UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.ReturnRecord", b =>
                {
                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithOne("ReturnRecord")
                        .HasForeignKey("DAL.Models.ReturnRecord", "FoundItemId")
                        .HasConstraintName("FK__ReturnRec__Found__1EA48E88");

                    b.HasOne("DAL.Models.LostItem", "LostItem")
                        .WithOne("ReturnRecord")
                        .HasForeignKey("DAL.Models.ReturnRecord", "LostItemId")
                        .HasConstraintName("FK_ReturnRecord_LostItem");

                    b.HasOne("DAL.Models.User", "Receiver")
                        .WithMany("ReturnRecords")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__ReturnRec__Recei__1CBC4616");

                    b.HasOne("DAL.Models.User", "StaffUser")
                        .WithMany("HandledReturnRecords")
                        .HasForeignKey("StaffUserId")
                        .HasConstraintName("FK_ReturnRecord_User_Staff");

                    b.Navigation("FoundItem");

                    b.Navigation("LostItem");

                    b.Navigation("Receiver");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("Users")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK_User_Campus");

                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleID__0A9D95DB");

                    b.Navigation("Campus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("FoundItems");

                    b.Navigation("ItemActionLogs");

                    b.Navigation("LostItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Navigation("FoundItems");

                    b.Navigation("LostItems");
                });

            modelBuilder.Entity("DAL.Models.ClaimRequest", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("DAL.Models.Evidence", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DAL.Models.FoundItem", b =>
                {
                    b.Navigation("ClaimRequests");

                    b.Navigation("Images");

                    b.Navigation("ItemActionLogs");

                    b.Navigation("ItemMatches");

                    b.Navigation("ReturnRecord");
                });

            modelBuilder.Entity("DAL.Models.ItemMatch", b =>
                {
                    b.Navigation("MatchHistories");
                });

            modelBuilder.Entity("DAL.Models.LostItem", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("Images");

                    b.Navigation("ItemActionLogs");

                    b.Navigation("ItemMatches");

                    b.Navigation("ReturnRecord");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("ClaimRequests");

                    b.Navigation("FoundItemCreatedByNavigations");

                    b.Navigation("FoundItemStoredByNavigations");

                    b.Navigation("HandledReturnRecords");

                    b.Navigation("Images");

                    b.Navigation("ItemActionLogs");

                    b.Navigation("ItemMatches");

                    b.Navigation("LostItems");

                    b.Navigation("MatchHistories");

                    b.Navigation("Notifications");

                    b.Navigation("ReturnRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
