// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(LostFoundTrackingSystemContext))]
    partial class LostFoundTrackingSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("CampusId")
                        .HasName("PK__Campus__FD598D36729196F6");

                    b.ToTable("Campus", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClaimID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<int>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ClaimId")
                        .HasName("PK__Claim__EF2E13BB6FD5146B");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("StudentId");

                    b.ToTable("Claim", (string)null);
                });

            modelBuilder.Entity("DAL.Models.FoundItem", b =>
                {
                    b.Property<int>("FoundItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoundItemId"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FoundLocation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StoredBy")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("FoundItemId")
                        .HasName("PK__FoundIte__DFA62C370CAF2C28");

                    b.HasIndex("CampusId");

                    b.HasIndex("StoredBy");

                    b.ToTable("FoundItem", (string)null);
                });

            modelBuilder.Entity("DAL.Models.LostItem", b =>
                {
                    b.Property<int>("LostItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LostItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LostItemId"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("CampusID");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LostDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("LostItemId")
                        .HasName("PK__LostItem__3B3BF432EB9C7F4F");

                    b.HasIndex("CampusId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("LostItem", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ReturnRecord", b =>
                {
                    b.Property<int>("ReturnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReturnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReturnId"));

                    b.Property<int>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("FoundItemID");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("ReceiverID");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.HasKey("ReturnId")
                        .HasName("PK__ReturnRe__F445E988E2C6B73A");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "FoundItemId" }, "UQ__ReturnRe__DFA62C368DFE4873")
                        .IsUnique();

                    b.ToTable("ReturnRecord", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A2D5E534F");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCAC7ADB6FA1");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105347BDC93EF")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Claim", b =>
                {
                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithMany("Claims")
                        .HasForeignKey("FoundItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Claim_Found");

                    b.HasOne("DAL.Models.User", "Student")
                        .WithMany("Claims")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Claim_User");

                    b.Navigation("FoundItem");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DAL.Models.FoundItem", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("FoundItems")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("FK_Found_Campus");

                    b.HasOne("DAL.Models.User", "StoredByNavigation")
                        .WithMany("FoundItems")
                        .HasForeignKey("StoredBy")
                        .IsRequired()
                        .HasConstraintName("FK_Found_User");

                    b.Navigation("Campus");

                    b.Navigation("StoredByNavigation");
                });

            modelBuilder.Entity("DAL.Models.LostItem", b =>
                {
                    b.HasOne("DAL.Models.Campus", "Campus")
                        .WithMany("LostItems")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("FK_Lost_Campus");

                    b.HasOne("DAL.Models.User", "CreatedByNavigation")
                        .WithMany("LostItems")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Lost_User");

                    b.Navigation("Campus");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("DAL.Models.ReturnRecord", b =>
                {
                    b.HasOne("DAL.Models.FoundItem", "FoundItem")
                        .WithOne("ReturnRecord")
                        .HasForeignKey("DAL.Models.ReturnRecord", "FoundItemId")
                        .IsRequired()
                        .HasConstraintName("FK_Return_Found");

                    b.HasOne("DAL.Models.User", "Receiver")
                        .WithMany("ReturnRecordReceivers")
                        .HasForeignKey("ReceiverId")
                        .IsRequired()
                        .HasConstraintName("FK_Return_Receiver");

                    b.HasOne("DAL.Models.User", "Staff")
                        .WithMany("ReturnRecordStaffs")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK_Return_Staff");

                    b.Navigation("FoundItem");

                    b.Navigation("Receiver");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.Campus", b =>
                {
                    b.Navigation("FoundItems");

                    b.Navigation("LostItems");
                });

            modelBuilder.Entity("DAL.Models.FoundItem", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ReturnRecord");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("FoundItems");

                    b.Navigation("LostItems");

                    b.Navigation("ReturnRecordReceivers");

                    b.Navigation("ReturnRecordStaffs");
                });
#pragma warning restore 612, 618
        }
    }
}
