// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Campus
{
    public int CampusId { get; set; }

    public string CampusName { get; set; }

    public string Address { get; set; }

    public string StorageLocation { get; set; }

    public virtual ICollection<Evidence> Evidences { get; set; } = new List<Evidence>();

    public virtual ICollection<FoundItem> FoundItems { get; set; } = new List<FoundItem>();

    public virtual ICollection<ItemActionLog> ItemActionLogs { get; set; } = new List<ItemActionLog>();

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}