// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Campus
{
    public int CampusId { get; set; }

    public string CampusName { get; set; }

    public string Address { get; set; }

    public virtual ICollection<FoundItem> FoundItems { get; set; } = new List<FoundItem>();

    public virtual ICollection<LostItem> LostItems { get; set; } = new List<LostItem>();

}