// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Claim
{
    public int ClaimId { get; set; }

    public DateTime ClaimDate { get; set; }

    public string Status { get; set; }

    public string Evidence { get; set; }

    public int StudentId { get; set; }

    public int FoundItemId { get; set; }

    public virtual FoundItem FoundItem { get; set; }

    public virtual User Student { get; set; }
}