// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Evidence
{
    public int EvidenceId { get; set; }

    public int? ClaimId { get; set; }

    public int? LostItemId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? CampusId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ClaimRequest Claim { get; set; }

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual LostItem LostItem { get; set; }
}