// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class FoundItem
{
    public int FoundItemId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? FoundDate { get; set; }

    public string FoundLocation { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public int? StoredBy { get; set; }

    public int? CampusId { get; set; }

    public int? CategoryId { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ItemCategory Category { get; set; }

    public virtual ICollection<ClaimRequest> ClaimRequests { get; set; } = new List<ClaimRequest>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<ItemActionLog> ItemActionLogs { get; set; } = new List<ItemActionLog>();

    public virtual ICollection<ItemMatch> ItemMatches { get; set; } = new List<ItemMatch>();

    public virtual ReturnRecord ReturnRecord { get; set; }

    public virtual User StoredByNavigation { get; set; }
}