// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class FoundItem
{
    public int FoundItemId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime FoundDate { get; set; }

    public string FoundLocation { get; set; }

    public string Status { get; set; }

    public int StoredBy { get; set; }

    public int CampusId { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ICollection<Claim> Claims { get; set; } = new List<Claim>();

    public virtual ReturnRecord ReturnRecord { get; set; }

    public virtual User StoredByNavigation { get; set; }
}