// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Image
{
    public int ImageId { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? UploadedAt { get; set; }

    public int? UploadedBy { get; set; }

    public int? FoundItemId { get; set; }

    public int? EvidenceId { get; set; }

    public virtual Evidence Evidence { get; set; }

    public virtual FoundItem FoundItem { get; set; }

    public virtual User UploadedByNavigation { get; set; }
}