// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ItemActionLog
{
    public int ActionId { get; set; }

    public int? LostItemId { get; set; }

    public int? FoundItemId { get; set; }

    public int? ClaimRequestId { get; set; }

    public string ActionType { get; set; }

    public string ActionDetails { get; set; }

    public string OldStatus { get; set; }

    public string NewStatus { get; set; }

    public DateTime? ActionDate { get; set; }

    public int? PerformedBy { get; set; }

    public int? CampusId { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual FoundItem FoundItem { get; set; }

    public virtual LostItem LostItem { get; set; }

    public virtual ClaimRequest ClaimRequest { get; set; }

    public virtual User PerformedByNavigation { get; set; }
}