// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ItemMatch
{
    public int MatchId { get; set; }

    public string MatchStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Status { get; set; }

    public int? FoundItemId { get; set; }

    public int? LostItemId { get; set; }

    public int? CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual FoundItem FoundItem { get; set; }

    public virtual LostItem LostItem { get; set; }

    public virtual ICollection<MatchHistory> MatchHistories { get; set; } = new List<MatchHistory>();
}