// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ItemCategory
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<FoundItem> FoundItems { get; set; } = new List<FoundItem>();

    public virtual ICollection<LostItem> LostItems { get; set; } = new List<LostItem>();
}