// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class LostItem
{
    public int LostItemId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime LostDate { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public int CreatedBy { get; set; }

    public int CampusId { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}