// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace DAL.Models;

public partial class LostFoundTrackingSystemContext : DbContext
{
    public LostFoundTrackingSystemContext()
    {
    }

    public LostFoundTrackingSystemContext(DbContextOptions<LostFoundTrackingSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Campus> Campuses { get; set; }

    public virtual DbSet<Claim> Claims { get; set; }

    public virtual DbSet<FoundItem> FoundItems { get; set; }

    public virtual DbSet<LostItem> LostItems { get; set; }

    public virtual DbSet<ReturnRecord> ReturnRecords { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            optionsBuilder.UseSqlServer(config.GetConnectionString("MyCnn"));
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Campus>(entity =>
        {
            entity.HasKey(e => e.CampusId).HasName("PK__Campus__FD598D36729196F6");

            entity.ToTable("Campus");

            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(254);
            entity.Property(e => e.CampusName)
                .IsRequired()
                .HasMaxLength(254);
        });

        modelBuilder.Entity<Claim>(entity =>
        {
            entity.HasKey(e => e.ClaimId).HasName("PK__Claim__EF2E13BB6FD5146B");

            entity.ToTable("Claim");

            entity.Property(e => e.ClaimId).HasColumnName("ClaimID");
            entity.Property(e => e.ClaimDate).HasColumnType("datetime");
            entity.Property(e => e.Evidence).HasColumnType("text");
            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StudentId).HasColumnName("StudentID");

            entity.HasOne(d => d.FoundItem).WithMany(p => p.Claims)
                .HasForeignKey(d => d.FoundItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Claim_Found");

            entity.HasOne(d => d.Student).WithMany(p => p.Claims)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Claim_User");
        });

        modelBuilder.Entity<FoundItem>(entity =>
        {
            entity.HasKey(e => e.FoundItemId).HasName("PK__FoundIte__DFA62C370CAF2C28");

            entity.ToTable("FoundItem");

            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.FoundDate).HasColumnType("datetime");
            entity.Property(e => e.FoundLocation)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Campus).WithMany(p => p.FoundItems)
                .HasForeignKey(d => d.CampusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Found_Campus");

            entity.HasOne(d => d.StoredByNavigation).WithMany(p => p.FoundItems)
                .HasForeignKey(d => d.StoredBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Found_User");
        });

        modelBuilder.Entity<LostItem>(entity =>
        {
            entity.HasKey(e => e.LostItemId).HasName("PK__LostItem__3B3BF432EB9C7F4F");

            entity.ToTable("LostItem");

            entity.Property(e => e.LostItemId).HasColumnName("LostItemID");
            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.Description).HasColumnType("text");
            entity.Property(e => e.Location)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.LostDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.Campus).WithMany(p => p.LostItems)
                .HasForeignKey(d => d.CampusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lost_Campus");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LostItems)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Lost_User");
        });

        modelBuilder.Entity<ReturnRecord>(entity =>
        {
            entity.HasKey(e => e.ReturnId).HasName("PK__ReturnRe__F445E988E2C6B73A");

            entity.ToTable("ReturnRecord");

            entity.HasIndex(e => e.FoundItemId, "UQ__ReturnRe__DFA62C368DFE4873").IsUnique();

            entity.Property(e => e.ReturnId).HasColumnName("ReturnID");
            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.ReceiverId).HasColumnName("ReceiverID");
            entity.Property(e => e.ReturnDate).HasColumnType("datetime");
            entity.Property(e => e.StaffId).HasColumnName("StaffID");

            entity.HasOne(d => d.FoundItem).WithOne(p => p.ReturnRecord)
                .HasForeignKey<ReturnRecord>(d => d.FoundItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_Found");

            entity.HasOne(d => d.Receiver).WithMany(p => p.ReturnRecordReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_Receiver");

            entity.HasOne(d => d.Staff).WithMany(p => p.ReturnRecordStaffs)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_Staff");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE3A2D5E534F");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(254);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CCAC7ADB6FA1");

            entity.ToTable("User");

            entity.HasIndex(e => e.Email, "UQ__User__A9D105347BDC93EF").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}