// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class LostItem
{
    public int LostItemId { get; set; }

    public DateTime? LostDate { get; set; }

    public string LostLocation { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<Evidence> Evidences { get; set; } = new List<Evidence>();

    public virtual ICollection<ItemActionLog> ItemActionLogs { get; set; } = new List<ItemActionLog>();

    public virtual ICollection<ItemMatch> ItemMatches { get; set; } = new List<ItemMatch>();
}