// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace DAL.Models;

public partial class LostFoundTrackingSystemContext : DbContext
{
    public LostFoundTrackingSystemContext()
    {
    }

    public LostFoundTrackingSystemContext(DbContextOptions<LostFoundTrackingSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Campus> Campuses { get; set; }

    public virtual DbSet<ClaimRequest> ClaimRequests { get; set; }

    public virtual DbSet<FoundItem> FoundItems { get; set; }

    public virtual DbSet<ItemActionLog> ItemActionLogs { get; set; }

    public virtual DbSet<ItemCategory> ItemCategories { get; set; }

    public virtual DbSet<ItemMatch> ItemMatches { get; set; }

    public virtual DbSet<LostItem> LostItems { get; set; }

    public virtual DbSet<MatchHistory> MatchHistories { get; set; }

    public virtual DbSet<ReturnRecord> ReturnRecords { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Staff> Staff { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            optionsBuilder.UseSqlServer(config.GetConnectionString("MyCnn"));
        }
    }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Campus>(entity =>
        {
            entity.HasKey(e => e.CampusId).HasName("PK__Campus__FD598D361FD90C0B");

            entity.ToTable("Campus");

            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CampusName).HasMaxLength(255);
            entity.Property(e => e.StorageLocation).HasMaxLength(255);
        });

        modelBuilder.Entity<ClaimRequest>(entity =>
        {
            entity.HasKey(e => e.ClaimId).HasName("PK__ClaimReq__EF2E13BB2256F299");

            entity.ToTable("ClaimRequest");

            entity.Property(e => e.ClaimId).HasColumnName("ClaimID");
            entity.Property(e => e.ClaimDate).HasColumnType("datetime");
            entity.Property(e => e.Evidence).HasMaxLength(255);
            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.StudentId).HasColumnName("StudentID");

            entity.HasOne(d => d.FoundItem).WithMany(p => p.ClaimRequests)
                .HasForeignKey(d => d.FoundItemId)
                .HasConstraintName("FK__ClaimRequ__Found__5CD6CB2B");

            entity.HasOne(d => d.Student).WithMany(p => p.ClaimRequests)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK__ClaimRequ__Stude__5DCAEF64");
        });

        modelBuilder.Entity<FoundItem>(entity =>
        {
            entity.HasKey(e => e.FoundItemId).HasName("PK__FoundIte__DFA62C373E8F104F");

            entity.ToTable("FoundItem");

            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.FoundDate).HasColumnType("datetime");
            entity.Property(e => e.FoundLocation).HasMaxLength(255);
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .HasColumnName("ImageURL");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.Campus).WithMany(p => p.FoundItems)
                .HasForeignKey(d => d.CampusId)
                .HasConstraintName("FK__FoundItem__Campu__5629CD9C");

            entity.HasOne(d => d.Category).WithMany(p => p.FoundItems)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__FoundItem__Categ__571DF1D5");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.FoundItemCreatedByNavigations)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__FoundItem__Creat__5441852A");

            entity.HasOne(d => d.StoredByNavigation).WithMany(p => p.FoundItemStoredByNavigations)
                .HasForeignKey(d => d.StoredBy)
                .HasConstraintName("FK__FoundItem__Store__5535A963");
        });

        modelBuilder.Entity<ItemActionLog>(entity =>
        {
            entity.HasKey(e => e.ActionId).HasName("PK__ItemActi__FFE3F4B942C6D547");

            entity.ToTable("ItemActionLog");

            entity.Property(e => e.ActionId).HasColumnName("ActionID");
            entity.Property(e => e.ActionDate).HasColumnType("datetime");
            entity.Property(e => e.ActionType).HasMaxLength(255);
            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.LostItemId).HasColumnName("LostItemID");
            entity.Property(e => e.NewStatus).HasMaxLength(255);
            entity.Property(e => e.OldStatus).HasMaxLength(255);

            entity.HasOne(d => d.Campus).WithMany(p => p.ItemActionLogs)
                .HasForeignKey(d => d.CampusId)
                .HasConstraintName("FK__ItemActio__Campu__6477ECF3");

            entity.HasOne(d => d.FoundItem).WithMany(p => p.ItemActionLogs)
                .HasForeignKey(d => d.FoundItemId)
                .HasConstraintName("FK__ItemActio__Found__628FA481");

            entity.HasOne(d => d.LostItem).WithMany(p => p.ItemActionLogs)
                .HasForeignKey(d => d.LostItemId)
                .HasConstraintName("FK__ItemActio__LostI__619B8048");

            entity.HasOne(d => d.PerformedByNavigation).WithMany(p => p.ItemActionLogs)
                .HasForeignKey(d => d.PerformedBy)
                .HasConstraintName("FK__ItemActio__Perfo__6383C8BA");
        });

        modelBuilder.Entity<ItemCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__ItemCate__19093A2BE89C763D");

            entity.ToTable("ItemCategory");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName).HasMaxLength(255);
        });

        modelBuilder.Entity<ItemMatch>(entity =>
        {
            entity.HasKey(e => e.MatchId).HasName("PK__ItemMatc__4218C8379CF38C11");

            entity.ToTable("ItemMatch");

            entity.Property(e => e.MatchId).HasColumnName("MatchID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.LostItemId).HasColumnName("LostItemID");
            entity.Property(e => e.MatchStatus).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(255);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.ItemMatches)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__ItemMatch__Creat__59FA5E80");

            entity.HasOne(d => d.FoundItem).WithMany(p => p.ItemMatches)
                .HasForeignKey(d => d.FoundItemId)
                .HasConstraintName("FK__ItemMatch__Found__5812160E");

            entity.HasOne(d => d.LostItem).WithMany(p => p.ItemMatches)
                .HasForeignKey(d => d.LostItemId)
                .HasConstraintName("FK__ItemMatch__LostI__59063A47");
        });

        modelBuilder.Entity<LostItem>(entity =>
        {
            entity.HasKey(e => e.LostItemId).HasName("PK__LostItem__3B3BF43275908D13");

            entity.ToTable("LostItem");

            entity.Property(e => e.LostItemId).HasColumnName("LostItemID");
            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .HasColumnName("ImageURL");
            entity.Property(e => e.LostDate).HasColumnType("datetime");
            entity.Property(e => e.LostLocation).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.Campus).WithMany(p => p.LostItems)
                .HasForeignKey(d => d.CampusId)
                .HasConstraintName("FK__LostItem__Campus__5165187F");

            entity.HasOne(d => d.Category).WithMany(p => p.LostItems)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__LostItem__Catego__534D60F1");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.LostItems)
                .HasForeignKey(d => d.CreatedBy)
                .HasConstraintName("FK__LostItem__Create__52593CB8");
        });

        modelBuilder.Entity<MatchHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__MatchHis__4D7B4ADD49D6DA61");

            entity.ToTable("MatchHistory");

            entity.Property(e => e.HistoryId).HasColumnName("HistoryID");
            entity.Property(e => e.Action).HasMaxLength(255);
            entity.Property(e => e.ActionDate).HasColumnType("datetime");
            entity.Property(e => e.MatchId).HasColumnName("MatchID");

            entity.HasOne(d => d.ActionByNavigation).WithMany(p => p.MatchHistories)
                .HasForeignKey(d => d.ActionBy)
                .HasConstraintName("FK__MatchHist__Actio__5BE2A6F2");

            entity.HasOne(d => d.Match).WithMany(p => p.MatchHistories)
                .HasForeignKey(d => d.MatchId)
                .HasConstraintName("FK__MatchHist__Match__5AEE82B9");
        });

        modelBuilder.Entity<ReturnRecord>(entity =>
        {
            entity.HasKey(e => e.ReturnId).HasName("PK__ReturnRe__F445E988875EA6ED");

            entity.ToTable("ReturnRecord");

            entity.HasIndex(e => e.FoundItemId, "UQ__ReturnRe__DFA62C367C929284").IsUnique();

            entity.Property(e => e.ReturnId).HasColumnName("ReturnID");
            entity.Property(e => e.FoundItemId).HasColumnName("FoundItemID");
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.ReceiverId).HasColumnName("ReceiverID");
            entity.Property(e => e.ReturnDate).HasColumnType("datetime");
            entity.Property(e => e.StaffId).HasColumnName("StaffID");

            entity.HasOne(d => d.FoundItem).WithOne(p => p.ReturnRecord)
                .HasForeignKey<ReturnRecord>(d => d.FoundItemId)
                .HasConstraintName("FK__ReturnRec__Found__60A75C0F");

            entity.HasOne(d => d.Receiver).WithMany(p => p.ReturnRecords)
                .HasForeignKey(d => d.ReceiverId)
                .HasConstraintName("FK__ReturnRec__Recei__5EBF139D");

            entity.HasOne(d => d.Staff).WithMany(p => p.ReturnRecords)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK__ReturnRec__Staff__5FB337D6");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE3A888B4D9F");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName).HasMaxLength(255);
        });

        modelBuilder.Entity<Staff>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("PK__Staff__96D4AAF72F5B8C88");

            entity.HasIndex(e => e.UserId, "UQ__Staff__1788CCAD9FC86D18").IsUnique();

            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.CampusId).HasColumnName("CampusID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Campus).WithMany(p => p.Staff)
                .HasForeignKey(d => d.CampusId)
                .HasConstraintName("FK__Staff__CampusID__5070F446");

            entity.HasOne(d => d.User).WithOne(p => p.Staff)
                .HasForeignKey<Staff>(d => d.UserId)
                .HasConstraintName("FK__Staff__UserID__4F7CD00D");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CCAC9CF4F3EF");

            entity.ToTable("User");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.PasswordHash).HasMaxLength(255);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status).HasMaxLength(255);
            entity.Property(e => e.Username).HasMaxLength(255);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__User__RoleID__4E88ABD4");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}