// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class MatchHistory
{
    public int HistoryId { get; set; }

    public string Action { get; set; }

    public DateTime? ActionDate { get; set; }

    public int? MatchId { get; set; }

    public int? ActionBy { get; set; }

    public virtual User ActionByNavigation { get; set; }

    public virtual ItemMatch Match { get; set; }
}