// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class ReturnRecord
{
    public int ReturnId { get; set; }

    public DateTime? ReturnDate { get; set; }

    public string Note { get; set; }

    public int? ReceiverId { get; set; }

    public int? StaffId { get; set; }

    public int? FoundItemId { get; set; }
    public int? LostItemId { get; set; }
    public virtual FoundItem FoundItem { get; set; }
    public virtual LostItem LostItem { get; set; }

    public virtual User Receiver { get; set; }

    public virtual Staff Staff { get; set; }
}