// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public int RoleId { get; set; }


    public virtual ICollection<Claim> Claims { get; set; } = new List<Claim>();

    public virtual ICollection<FoundItem> FoundItems { get; set; } = new List<FoundItem>();

    public virtual ICollection<LostItem> LostItems { get; set; } = new List<LostItem>();

    public virtual ICollection<ReturnRecord> ReturnRecordReceivers { get; set; } = new List<ReturnRecord>();

    public virtual ICollection<ReturnRecord> ReturnRecordStaffs { get; set; } = new List<ReturnRecord>();

    public virtual Role Role { get; set; }
}