// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string FullName { get; set; }

    public string Status { get; set; }
    public string PhoneNumber { get; set; } 

    public int? RoleId { get; set; }

    public int? CampusId { get; set; }
    public string? StudentIdCardUrl { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ICollection<ClaimRequest> ClaimRequests { get; set; } = new List<ClaimRequest>();

    public virtual ICollection<FoundItem> FoundItemCreatedByNavigations { get; set; } = new List<FoundItem>();

    public virtual ICollection<FoundItem> FoundItemStoredByNavigations { get; set; } = new List<FoundItem>();

    public virtual ICollection<Image> Images { get; set; } = new List<Image>();

    public virtual ICollection<ItemActionLog> ItemActionLogs { get; set; } = new List<ItemActionLog>();

    public virtual ICollection<ItemMatch> ItemMatches { get; set; } = new List<ItemMatch>();

    public virtual ICollection<LostItem> LostItems { get; set; } = new List<LostItem>();

    public virtual ICollection<MatchHistory> MatchHistories { get; set; } = new List<MatchHistory>();

        public virtual ICollection<ReturnRecord> ReturnRecords { get; set; } = new List<ReturnRecord>();

        public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

        public virtual ICollection<ReturnRecord> HandledReturnRecords { get; set; } = new List<ReturnRecord>();

    

    

        public virtual Role Role { get; set; }

    }

    